    - name: Create artifact directory
      run: mkdir artifact

    - name: Copy coverage report to artifact directory
      run: cp ${{ inputs.coverage-file || 'coverage-report' }}.html artifact/

    - name: Upload coverage report artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: artifact

    - name: Comment coverage report link
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          const url = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/deployments/activity_log?environment=github-pages`;
          const issueNumber = context.issue.number;
          const repo = context.repo.repo;
          const owner = context.repo.owner;

          github.issues.createComment({
            issue_number: issueNumber,
            owner,
            repo,
            body: `See the coverage report at: [Deployment Log](${url})`
          });