name: Go Coverage Report
description: |
  This action runs code coverage for Go based projects, uploads the coverage report as an artifact, and comments on the pull request with the link to the deployed coverage report.
author: sonichigo
branding:
  icon: 'refresh-cw'
  color: 'orange'

inputs:
  package-directory:
    description: 'Package directory to run tests'
    required: false
    default: './...'
  coverage-file:
    description: 'Name of the coverage file (without extension)'
    required: false
    default: 'coverage-report'
  coverage-threshold:
    description: 'Minimum coverage percentage required.'
    required: false
    default: '80'
  token:
    description: 'Token with Deployment Permissions'
    required: true

outputs:
  coverage-report-file:
    description: 'Path to the generated coverage report file'
    value: ${{ steps.generate-report.outputs.report-file }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.*

    - name: Generate coverage report
      run: |
        PKG_DIR="${{ inputs.package-directory || './...' }}"
        COVERAGE_FILE="${{ inputs.coverage-file || 'coverage-report' }}"
        go test -race -coverprofile=$COVERAGE_FILE.out $PKG_DIR
        go tool cover -html=$COVERAGE_FILE.out -o $COVERAGE_FILE.html
        COVERAGE_PERCENTAGE=$(go tool cover -func=$COVERAGE_FILE.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
        if (( $(echo "$COVERAGE_PERCENTAGE < ${{ inputs.coverage-threshold }}" | bc -l) )); then
          echo "Error: Coverage $COVERAGE_PERCENTAGE% is below the required threshold of ${{ inputs.coverage-threshold }}%"
          exit 1
        fi
        echo "report-file=$COVERAGE_FILE.html" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get coverage data as ZIP
      if: success()
      id: coverage-zip
      run: |
        workdir="${{ inputs.package-directory }}"
        workdir="${workdir//\\//-}"
        workdir="${workdir%-}"
        coverage="coverage-reports-${workdir}-${{ inputs.coverage-file }}"
        mv ${{ inputs.coverage-file }}.html ./$coverage
        echo "coverage=$coverage"
        echo "::set-output name=coverage_name::$coverage"
        zip -r ${coverage}.zip $coverage
      shell: bash

    - name: Upload coverage zip as artifact
      if: steps.coverage-zip.outputs.coverage_name != ''
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.coverage-file }}
        path: ${{ steps.generate-report.outputs.report-file }}

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3

    - name: Comment coverage report link
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const url = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/deployments/activity_log?environment=github-pages`;
          const issueNumber = context.issue.number;
          const repo = context.repo.repo;
          const owner = context.repo.owner;

          github.issues.createComment({
            issue_number: issueNumber,
            owner,
            repo,
            body: `See the coverage report at: [Deployment Log](${url})`
          });